CREATE OR REPLACE FUNCTION generate_four_digit_auth_code() RETURNS TEXT AS $$ BEGIN RETURN CAST(FLOOR(1000 + RANDOM() * 9000) AS TEXT); END; $$ LANGUAGE plpgsql;
CREATE SCHEMA IF NOT EXISTS "hr";
CREATE SCHEMA IF NOT EXISTS "transport";
CREATE SCHEMA IF NOT EXISTS "chat";
CREATE SCHEMA IF NOT EXISTS "system";
CREATE TABLE IF NOT EXISTS "hr"."auth_code" (
	"id" SERIAL NOT NULL PRIMARY KEY UNIQUE,
	"user_id" INTEGER NOT NULL,
	"code" TEXT NOT NULL DEFAULT generate_four_digit_auth_code(),
	"active" BOOLEAN NULL DEFAULT TRUE,
	"created_in" TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_in" TIMESTAMP NULL,
	"inactivated_in" TIMESTAMP NULL
);
CREATE TABLE IF NOT EXISTS "hr"."contact_type" (
	"id" SERIAL NOT NULL PRIMARY KEY UNIQUE,
	"name" TEXT NOT NULL UNIQUE,
	"label" TEXT NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS "hr"."document" (
	"id" SERIAL NOT NULL PRIMARY KEY UNIQUE,
	"user_id" INTEGER NOT NULL,
	"document_type" INTEGER NOT NULL,
	"document" TEXT NOT NULL UNIQUE,
	"active" BOOLEAN NULL DEFAULT TRUE,
	"created_in" TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_in" TIMESTAMP NULL,
	"inactivated_in" TIMESTAMP NULL
);
CREATE TABLE IF NOT EXISTS "hr"."document_type" (
	"id" SERIAL NOT NULL PRIMARY KEY UNIQUE,
	"name" TEXT NOT NULL UNIQUE,
	"label" TEXT NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS "hr"."session" (
	"id" SERIAL NOT NULL PRIMARY KEY UNIQUE,
	"user_id" INTEGER NOT NULL,
	"token" TEXT NOT NULL,
	"active" BOOLEAN NULL DEFAULT TRUE,
	"created_in" TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_in" TIMESTAMP NULL,
	"inactivated_in" TIMESTAMP NULL
);
CREATE TABLE IF NOT EXISTS "hr"."user" (
	"id" SERIAL NOT NULL PRIMARY KEY UNIQUE,
	"name" TEXT NOT NULL,
	"number" TEXT NOT NULL UNIQUE,
	"password" TEXT NOT NULL,
	"authenticated" BOOLEAN NULL DEFAULT FALSE,
	"active" BOOLEAN NOT NULL DEFAULT TRUE,
	"created_in" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_in" TIMESTAMP NULL,
	"inactivated_in" TIMESTAMP NULL
);
CREATE TABLE IF NOT EXISTS "hr"."user_settings" (
	"id" SERIAL NOT NULL PRIMARY KEY UNIQUE,
	"user_id" INTEGER NULL UNIQUE,
	"theme" TEXT NULL,
	"language" TEXT NULL
);
CREATE TABLE IF NOT EXISTS "transport"."machinery" (
	"id" SERIAL NOT NULL PRIMARY KEY UNIQUE,
	"user_id" INTEGER NOT NULL,
	"name" TEXT NOT NULL,
	"model" TEXT NOT NULL,
	"plate" TEXT NOT NULL UNIQUE,
	"active" BOOLEAN NULL DEFAULT TRUE,
	"created_in" TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_in" TIMESTAMP NULL,
	"inactivated_in" TIMESTAMP NULL
);
CREATE TABLE IF NOT EXISTS "transport"."offer" (
	"id" SERIAL NOT NULL PRIMARY KEY UNIQUE,
	"user_id" INTEGER NOT NULL,
	"request_id" INTEGER NOT NULL,
	"carrier_id" INTEGER NOT NULL,
	"price" NUMERIC NOT NULL,
	"active" BOOLEAN NULL DEFAULT TRUE,
	"created_in" TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_in" TIMESTAMP NULL,
	"inactivated_in" TIMESTAMP NULL
);
CREATE TABLE IF NOT EXISTS "transport"."request" (
	"id" SERIAL NOT NULL PRIMARY KEY UNIQUE,
	"user_id" INTEGER NOT NULL,
	"origin" TEXT NOT NULL,
	"destination" TEXT NOT NULL,
	"desired_date" TIMESTAMP NOT NULL,
	"active" BOOLEAN NULL DEFAULT TRUE,
	"created_in" TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_in" TIMESTAMP NULL,
	"inactivated_in" TIMESTAMP NULL
);
CREATE TABLE IF NOT EXISTS "transport"."carrier" (
	"id" SERIAL NOT NULL PRIMARY KEY UNIQUE,
	"user_id" INTEGER NOT NULL,
	"name" TEXT NOT NULL,
	"model" TEXT NOT NULL,
	"plate" TEXT NOT NULL UNIQUE,
	"active" BOOLEAN NULL DEFAULT TRUE,
	"created_in" TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_in" TIMESTAMP NULL,
	"inactivated_in" TIMESTAMP NULL
);
CREATE TABLE IF NOT EXISTS "chat"."message" (
	"id" SERIAL NOT NULL PRIMARY KEY UNIQUE,
	"from_user_id" INTEGER NOT NULL,
	"to_user_id" INTEGER NOT NULL,
	"answer_to" INTEGER NULL,
	"message" TEXT NOT NULL,
	"active" BOOLEAN NULL DEFAULT TRUE,
	"created_in" TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_in" TIMESTAMP NULL,
	"inactivated_in" TIMESTAMP NULL
);
CREATE TABLE IF NOT EXISTS "system"."error_log" (
	"id" SERIAL NOT NULL PRIMARY KEY UNIQUE,
	"json" TEXT NOT NULL,
	"params" TEXT NOT NULL,
	"created_in" TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);
