services:
  agrofast-nginx:
    container_name: agrofast-nginx
    image: nginx:1.27.1
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html/app
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - agrofast-php-fpm
    environment:
      - SERVER_NAME=agrofast.api.com
    networks:
      - app-network

  agrofast-php-fpm:
    container_name: agrofast-php-fpm
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html/app
    depends_on:
      - agrofast-postgres
    networks:
      - app-network

  agrofast-postgres:
    container_name: agrofast-postgres
    image: postgres:17
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
