version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agrofast-api
    volumes:
      - .:/var/www/html/app
    ports:
      - "9000:9000"
      - "80:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge