services:
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        ports:
            - "9010:80"
        volumes:
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www:delegated
        depends_on:
            - php
        networks:
            - laravel

    php-fpm:
        build:
            context: .
            dockerfile: Dockerfile.prod.php
        restart: unless-stopped
        tty: true
        expose:
            - "9000"
        volumes:
            - .:/var/www:delegated
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
