services:
    php:
        build:
            context: .
            dockerfile: Dockerfile.prod.php
        container_name: php
        restart: unless-stopped
        tty: true
        expose:
            - "9010:9000"
        volumes:
            - .:/var/www:delegated
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
