services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - .:/var/www/html/agrofast
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - SERVER_NAME=${SERVER_NAME}
    depends_on:
      - php-fpm
  php-fpm:
    container_name: php-fpm
    image: php:8.1-fpm
    volumes:
      - .:/var/www/html/agrofast
