services:
  nginx:
    container_name: nginx
    image: nginx:1.27.1
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html/app
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    environment:
      - SERVER_NAME=agrofast.api.com
    networks:
      - app-network

  php-fpm:
    container_name: php-fpm
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html/app
    networks:
      - app-network

  postgres:
    container_name: postgres
    image: postgres:17
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
