services:
    agrofast-nginx:
        container_name: agrofast-nginx
        image: nginx:alpine
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ../docker/config/nginx/conf.d/api.conf:/etc/nginx/conf.d/api.conf
            - ../docker/config/nginx/conf.d/console.conf:/etc/nginx/conf.d/console.conf
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - agrofast-network

    agrofast-php-fpm:
        container_name: agrofast-php-fpm
        extends:
            file: ../docker-compose.yml
            service: agrofast-php-fpm

    agrofast-postgres:
        container_name: agrofast-postgres
        extends:
            file: ../docker-compose.yml
            service: agrofast-postgres

    agrofast-minio:
        container_name: agrofast-minio
        extends:
            file: ../docker-compose.yml
            service: agrofast-minio

    agrofast-redis:
        container_name: agrofast-redis
        extends:
            file: ../docker-compose.yml
            service: agrofast-redis

volumes:
    postgres_data:
    minio_data:
    cache:
        driver: local

networks:
    agrofast-network:
        driver: bridge
    mapdata-network:
        external: true
