services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - "8080:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www:delegated
        depends_on:
            - php
        networks:
            - laravel

    php:
        build:
            context: .
            dockerfile: Dockerfile.prod.php
        container_name: php
        restart: unless-stopped
        tty: true
        expose:
            - "9000"
        volumes:
            - .:/var/www:delegated
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
