services:
  api:
    container_name: agrofast-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    working_dir: /var/www

    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - database
      - httpserver

  database:
    container_name: agrofast-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: $DB_DATABASE
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /data/postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  httpserver:
    container_name: agrofast-nginx
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d

volumes:
  postgres:
  cache:
    driver: local
