services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - app-network

  php-fpm:
    container_name: php-fpm
    image: php:8.2-fpm
    volumes:
      - .:/var/www/html/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
